version: '3'
services:
  app:
    image: ruby:2.6.5
    command: bundle exec rspec
    working_dir: /app
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true

volumes:
  bundle:
